name: Daily Reminder

on:
  schedule:
    # '분 시 일 월 요일(0:일 ~ 6:토)'
    - cron: '45 7 * * 1-5'
    # 수동 실행을 위한 트리거 추가
  workflow_dispatch:

jobs:
  send-daily-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Mattermost Notification
        env:
          MATTERMOST_URL: ${{secrets.MATTERMOST_WEBHOOK_URL}}
        run: |
          curl -i -X POST \
          -H 'Content-Type: application/json' \
          -d '{"text": "⏰ 오늘의 TIL 작성 시간입니다! 오늘 하루도 고생 많으셨습니다. 마무리 잘 하시고 즐거운 저녁 되세요!", "username":"TIL 봇"}' \
          "$MATTERMOST_URL"
